export type InitiativeStatus = 'open' | 'funded' | 'failed' | 'canceled';

export interface Initiative {
  id: string;
  title: string;
  description: string;
  goalAmount: number;
  heldAmount: number;
  deadline: Date;
  location: { address: string; lat: number; lng: number };
  organizer: { name: string; avatar: string };
  status: InitiativeStatus;
  community: string;
  pledgeCount: number;
  updates: { date: Date; text: string }[];
  pledgers: { name: string; avatar: string; amount: number }[];
}

const now = new Date();
const hoursFromNow = (h: number) => new Date(now.getTime() + h * 60 * 60 * 1000);

export const mockInitiatives: Initiative[] = [
  {
    id: '1',
    title: 'Community Garden Renovation',
    description: 'Transform the abandoned lot on Elm Street into a vibrant community garden with raised beds, composting stations, and a small greenhouse. This project will bring fresh produce to our neighborhood and create a gathering space for all ages.',
    goalAmount: 5000,
    heldAmount: 3750,
    deadline: hoursFromNow(72),
    location: { address: 'Elm Street, London', lat: 51.5074, lng: -0.1278 },
    organizer: { name: 'Sarah Chen', avatar: '' },
    status: 'open',
    community: 'Green London',
    pledgeCount: 24,
    updates: [
      { date: hoursFromNow(-24), text: 'We\'ve secured the land permit! Moving forward with the design phase.' },
      { date: hoursFromNow(-48), text: 'Initial community meeting held. 40+ attendees excited about the project!' },
    ],
    pledgers: [
      { name: 'James W.', avatar: '', amount: 250 },
      { name: 'Maria L.', avatar: '', amount: 100 },
      { name: 'Tom R.', avatar: '', amount: 500 },
      { name: 'Lisa K.', avatar: '', amount: 75 },
    ],
  },
  {
    id: '2',
    title: 'Youth Coding Workshop',
    description: 'Fund a week-long intensive coding workshop for underserved youth ages 12-18. Includes laptops, curriculum materials, and instructor fees.',
    goalAmount: 3000,
    heldAmount: 3000,
    deadline: hoursFromNow(-2),
    location: { address: 'Community Center, Manchester', lat: 53.4808, lng: -2.2426 },
    organizer: { name: 'David Park', avatar: '' },
    status: 'funded',
    community: 'TechForAll',
    pledgeCount: 42,
    updates: [
      { date: hoursFromNow(-1), text: '🎉 We did it! Goal reached! Workshop dates will be announced soon.' },
    ],
    pledgers: [
      { name: 'Anna B.', avatar: '', amount: 500 },
      { name: 'Chris M.', avatar: '', amount: 200 },
    ],
  },
  {
    id: '3',
    title: 'Street Art Festival',
    description: 'Organize a weekend street art festival featuring 15 local artists. Funds cover supplies, permits, and artist stipends.',
    goalAmount: 8000,
    heldAmount: 1200,
    deadline: hoursFromNow(-1),
    location: { address: 'Brick Lane, London', lat: 51.5215, lng: -0.0722 },
    organizer: { name: 'Mika Jones', avatar: '' },
    status: 'failed',
    community: 'Art Collective',
    pledgeCount: 8,
    updates: [],
    pledgers: [
      { name: 'Pat S.', avatar: '', amount: 300 },
    ],
  },
  {
    id: '4',
    title: 'Dog Park Cleanup Drive',
    description: 'Hire professional cleaners and purchase new waste stations for the Riverside Dog Park. Keep our furry friends\' space safe and clean.',
    goalAmount: 1500,
    heldAmount: 800,
    deadline: hoursFromNow(18),
    location: { address: 'Riverside Park, Bristol', lat: 51.4545, lng: -2.5879 },
    organizer: { name: 'Rachel Green', avatar: '' },
    status: 'open',
    community: 'Bristol Pet Lovers',
    pledgeCount: 15,
    updates: [
      { date: hoursFromNow(-12), text: 'Cleanup crew booked for next Saturday!' },
    ],
    pledgers: [
      { name: 'Mark D.', avatar: '', amount: 100 },
      { name: 'Sue T.', avatar: '', amount: 50 },
    ],
  },
  {
    id: '5',
    title: 'Mobile Library for Rural Areas',
    description: 'Purchase and outfit a van as a mobile library serving three rural communities with limited access to books and educational resources.',
    goalAmount: 12000,
    heldAmount: 4500,
    deadline: hoursFromNow(120),
    location: { address: 'Cotswolds, Gloucestershire', lat: 51.8330, lng: -1.8433 },
    organizer: { name: 'Emma White', avatar: '' },
    status: 'open',
    community: 'Rural Reads',
    pledgeCount: 31,
    updates: [
      { date: hoursFromNow(-36), text: 'Found a great van candidate! Negotiating price.' },
    ],
    pledgers: [
      { name: 'Oliver H.', avatar: '', amount: 1000 },
      { name: 'Nina P.', avatar: '', amount: 250 },
      { name: 'George K.', avatar: '', amount: 150 },
    ],
  },
  {
    id: '6',
    title: 'Temple Bar Busking Stage',
    description: 'Build a permanent covered busking stage in Temple Bar to support Dublin\'s street musicians. Includes weather protection, basic sound equipment, and scheduled performance slots.',
    goalAmount: 7500,
    heldAmount: 2800,
    deadline: hoursFromNow(96),
    location: { address: 'Temple Bar, Dublin', lat: 53.3457, lng: -6.2643 },
    organizer: { name: 'Ciarán O\'Brien', avatar: '' },
    status: 'open',
    community: 'Dublin Arts',
    pledgeCount: 37,
    updates: [
      { date: hoursFromNow(-18), text: 'Dublin City Council gave preliminary approval for the location!' },
    ],
    pledgers: [
      { name: 'Aoife M.', avatar: '', amount: 200 },
      { name: 'Sean K.', avatar: '', amount: 150 },
    ],
  },
  {
    id: '7',
    title: 'Phoenix Park Wildflower Meadow',
    description: 'Transform a section of Phoenix Park into a native wildflower meadow to support pollinators and biodiversity. Includes seed sourcing, soil prep, and interpretive signage.',
    goalAmount: 4000,
    heldAmount: 4000,
    deadline: hoursFromNow(-5),
    location: { address: 'Phoenix Park, Dublin', lat: 53.3558, lng: -6.3298 },
    organizer: { name: 'Niamh Gallagher', avatar: '' },
    status: 'funded',
    community: 'Green Dublin',
    pledgeCount: 52,
    updates: [
      { date: hoursFromNow(-3), text: '🎉 Fully funded! Planting begins next month.' },
    ],
    pledgers: [
      { name: 'Rory D.', avatar: '', amount: 500 },
      { name: 'Fiona L.', avatar: '', amount: 300 },
    ],
  },
  {
    id: '8',
    title: 'Docklands Youth Swim Club',
    description: 'Fund swimming lessons and pool access for 50 young people in the Dublin Docklands area who currently have no affordable access to learn to swim.',
    goalAmount: 3500,
    heldAmount: 1100,
    deadline: hoursFromNow(48),
    location: { address: 'Grand Canal Dock, Dublin', lat: 53.3389, lng: -6.2285 },
    organizer: { name: 'Declan Murphy', avatar: '' },
    status: 'open',
    community: 'Docklands Community',
    pledgeCount: 19,
    updates: [
      { date: hoursFromNow(-8), text: 'Partnered with a local pool for discounted rates!' },
    ],
    pledgers: [
      { name: 'Maeve C.', avatar: '', amount: 100 },
      { name: 'Paddy W.', avatar: '', amount: 75 },
    ],
  },
  {
    id: '9',
    title: 'Solar Panels for School',
    description: 'Install rooftop solar panels on a public school to cut energy costs and teach students about renewable energy.',
    goalAmount: 15000, heldAmount: 9200, deadline: hoursFromNow(200),
    location: { address: 'Brooklyn, New York', lat: 40.6782, lng: -73.9442 },
    organizer: { name: 'Marcus Johnson', avatar: '' }, status: 'open', community: 'NYC Green Schools', pledgeCount: 64,
    updates: [{ date: hoursFromNow(-10), text: 'Contractor selected. Installation planned for spring.' }],
    pledgers: [{ name: 'Tanya R.', avatar: '', amount: 500 }],
  },
  {
    id: '10',
    title: 'Beehive Network',
    description: 'Set up urban beehives across rooftops in Paris to boost pollination and produce local honey for community markets.',
    goalAmount: 6000, heldAmount: 6000, deadline: hoursFromNow(-10),
    location: { address: 'Le Marais, Paris', lat: 48.8566, lng: 2.3522 },
    organizer: { name: 'Claire Dupont', avatar: '' }, status: 'funded', community: 'Paris Verte', pledgeCount: 48,
    updates: [{ date: hoursFromNow(-5), text: '🎉 Funded! First hives arriving next week.' }],
    pledgers: [{ name: 'Jean-Luc M.', avatar: '', amount: 300 }],
  },
  {
    id: '11',
    title: 'Ocean Plastic Cleanup',
    description: 'Fund a week-long beach and coastal cleanup operation along the coast near Cape Town with volunteer coordination and equipment.',
    goalAmount: 4500, heldAmount: 1800, deadline: hoursFromNow(60),
    location: { address: 'Muizenberg, Cape Town', lat: -34.1085, lng: 18.4696 },
    organizer: { name: 'Thabo Ndlovu', avatar: '' }, status: 'open', community: 'Cape Cleaners', pledgeCount: 22,
    updates: [], pledgers: [{ name: 'Lerato K.', avatar: '', amount: 150 }],
  },
  {
    id: '12',
    title: 'Free Music Lessons for Kids',
    description: 'Provide free weekly music lessons for children in underserved neighborhoods in São Paulo. Covers instruments, teachers, and venue.',
    goalAmount: 5500, heldAmount: 3100, deadline: hoursFromNow(90),
    location: { address: 'Vila Madalena, São Paulo', lat: -23.5505, lng: -46.6333 },
    organizer: { name: 'Ana Silva', avatar: '' }, status: 'open', community: 'Música para Todos', pledgeCount: 35,
    updates: [{ date: hoursFromNow(-20), text: 'Secured a community hall for rehearsals.' }],
    pledgers: [{ name: 'Carlos R.', avatar: '', amount: 200 }],
  },
  {
    id: '13',
    title: 'Coral Reef Restoration',
    description: 'Plant 500 coral fragments on degraded reef sections near the Great Barrier Reef with marine biologists and volunteer divers.',
    goalAmount: 20000, heldAmount: 8500, deadline: hoursFromNow(300),
    location: { address: 'Cairns, Australia', lat: -16.9186, lng: 145.7781 },
    organizer: { name: 'Liam O\'Connor', avatar: '' }, status: 'open', community: 'Reef Revival', pledgeCount: 71,
    updates: [{ date: hoursFromNow(-48), text: 'Marine permit approved by Queensland authorities.' }],
    pledgers: [{ name: 'Sophie T.', avatar: '', amount: 1000 }],
  },
  {
    id: '14',
    title: 'Earthquake Relief Shelter Kits',
    description: 'Assemble and distribute emergency shelter kits to families affected by recent earthquakes in rural Turkey.',
    goalAmount: 10000, heldAmount: 10000, deadline: hoursFromNow(-20),
    location: { address: 'Antakya, Turkey', lat: 36.2025, lng: 36.1606 },
    organizer: { name: 'Elif Yılmaz', avatar: '' }, status: 'funded', community: 'Turkey Relief', pledgeCount: 93,
    updates: [{ date: hoursFromNow(-15), text: '🎉 Fully funded. First batch of kits shipped.' }],
    pledgers: [{ name: 'Ahmet K.', avatar: '', amount: 500 }],
  },
  {
    id: '15',
    title: 'Skatepark for Nairobi Youth',
    description: 'Build a concrete skatepark in Nairobi to give young people a safe recreational space and foster a skateboarding community.',
    goalAmount: 8000, heldAmount: 2400, deadline: hoursFromNow(150),
    location: { address: 'Westlands, Nairobi', lat: -1.2921, lng: 36.8219 },
    organizer: { name: 'James Ochieng', avatar: '' }, status: 'open', community: 'Skate Nairobi', pledgeCount: 18,
    updates: [], pledgers: [{ name: 'Wanjiku M.', avatar: '', amount: 200 }],
  },
  {
    id: '16',
    title: 'Winter Coat Drive',
    description: 'Collect and distribute 1,000 winter coats to homeless shelters across Chicago before the cold season hits.',
    goalAmount: 3000, heldAmount: 500, deadline: hoursFromNow(-5),
    location: { address: 'South Side, Chicago', lat: 41.8781, lng: -87.6298 },
    organizer: { name: 'Derek Williams', avatar: '' }, status: 'failed', community: 'Chicago Cares', pledgeCount: 6,
    updates: [], pledgers: [{ name: 'Maria G.', avatar: '', amount: 100 }],
  },
  {
    id: '17',
    title: 'Public Water Fountain Network',
    description: 'Install 20 free public drinking water fountains across downtown Tokyo to reduce plastic bottle waste.',
    goalAmount: 12000, heldAmount: 7800, deadline: hoursFromNow(80),
    location: { address: 'Shibuya, Tokyo', lat: 35.6762, lng: 139.6503 },
    organizer: { name: 'Yuki Tanaka', avatar: '' }, status: 'open', community: 'Tokyo Zero Waste', pledgeCount: 55,
    updates: [{ date: hoursFromNow(-30), text: 'City approved 12 of the 20 proposed locations.' }],
    pledgers: [{ name: 'Haruto S.', avatar: '', amount: 400 }],
  },
  {
    id: '18',
    title: 'Refugee Language Classes',
    description: 'Fund 6 months of free German language classes for refugees in Berlin, including materials and childcare during sessions.',
    goalAmount: 7000, heldAmount: 7000, deadline: hoursFromNow(-8),
    location: { address: 'Kreuzberg, Berlin', lat: 52.4990, lng: 13.4031 },
    organizer: { name: 'Hannah Müller', avatar: '' }, status: 'funded', community: 'Berlin Welcomes', pledgeCount: 61,
    updates: [{ date: hoursFromNow(-4), text: '🎉 Goal reached! Classes start next Monday.' }],
    pledgers: [{ name: 'Felix W.', avatar: '', amount: 350 }],
  },
  {
    id: '19',
    title: 'Mangrove Planting Drive',
    description: 'Plant 10,000 mangrove seedlings along the coast near Mumbai to protect against flooding and restore marine habitats.',
    goalAmount: 9000, heldAmount: 3200, deadline: hoursFromNow(180),
    location: { address: 'Versova, Mumbai', lat: 19.0760, lng: 72.8777 },
    organizer: { name: 'Priya Sharma', avatar: '' }, status: 'open', community: 'Mumbai Green Coast', pledgeCount: 40,
    updates: [{ date: hoursFromNow(-25), text: 'Nursery partner confirmed 5,000 seedlings ready.' }],
    pledgers: [{ name: 'Raj P.', avatar: '', amount: 250 }],
  },
  {
    id: '20',
    title: 'Street Library Boxes',
    description: 'Build and install 50 little free library boxes across neighborhoods in Buenos Aires to encourage reading and book sharing.',
    goalAmount: 2500, heldAmount: 2100, deadline: hoursFromNow(24),
    location: { address: 'Palermo, Buenos Aires', lat: -34.6037, lng: -58.3816 },
    organizer: { name: 'Lucía Fernández', avatar: '' }, status: 'open', community: 'BA Reads', pledgeCount: 33,
    updates: [{ date: hoursFromNow(-6), text: 'First 20 boxes built and painted by volunteers!' }],
    pledgers: [{ name: 'Mateo G.', avatar: '', amount: 100 }],
  },
  {
    id: '21',
    title: 'Community Bike Repair Hub',
    description: 'Open a free bike repair workshop in Amsterdam where locals can fix their bikes with donated tools and volunteer mechanics.',
    goalAmount: 4000, heldAmount: 3800, deadline: hoursFromNow(12),
    location: { address: 'Jordaan, Amsterdam', lat: 52.3676, lng: 4.9041 },
    organizer: { name: 'Daan de Vries', avatar: '' }, status: 'open', community: 'Bike Amsterdam', pledgeCount: 44,
    updates: [{ date: hoursFromNow(-3), text: 'Almost there! Just €200 to go.' }],
    pledgers: [{ name: 'Eva B.', avatar: '', amount: 150 }],
  },
  {
    id: '22',
    title: 'Indigenous Art Exhibition',
    description: 'Fund an exhibition showcasing indigenous art from across Canada in a downtown Vancouver gallery. Includes artist travel and accommodation.',
    goalAmount: 11000, heldAmount: 4200, deadline: hoursFromNow(140),
    location: { address: 'Gastown, Vancouver', lat: 49.2827, lng: -123.1207 },
    organizer: { name: 'Nathan Crow', avatar: '' }, status: 'open', community: 'First Nations Arts', pledgeCount: 28,
    updates: [], pledgers: [{ name: 'Maya L.', avatar: '', amount: 500 }],
  },
  {
    id: '23',
    title: 'Rooftop Farm Expansion',
    description: 'Expand an existing rooftop farm in Singapore to double its capacity, adding hydroponic systems and a composting area.',
    goalAmount: 8500, heldAmount: 8500, deadline: hoursFromNow(-12),
    location: { address: 'Chinatown, Singapore', lat: 1.3521, lng: 103.8198 },
    organizer: { name: 'Wei Lin', avatar: '' }, status: 'funded', community: 'SG Urban Farms', pledgeCount: 58,
    updates: [{ date: hoursFromNow(-6), text: '🎉 Funded! Construction begins in 2 weeks.' }],
    pledgers: [{ name: 'Kai T.', avatar: '', amount: 600 }],
  },
  {
    id: '24',
    title: 'Senior Tech Literacy Program',
    description: 'Teach seniors in Mexico City how to use smartphones, video calls, and online banking through free weekly workshops.',
    goalAmount: 3500, heldAmount: 900, deadline: hoursFromNow(100),
    location: { address: 'Coyoacán, Mexico City', lat: 19.4326, lng: -99.1332 },
    organizer: { name: 'Rosa Hernández', avatar: '' }, status: 'open', community: 'Digital Abuelos', pledgeCount: 12,
    updates: [], pledgers: [{ name: 'Pedro V.', avatar: '', amount: 75 }],
  },
  {
    id: '25',
    title: 'Floating Classroom',
    description: 'Convert a decommissioned ferry in Stockholm into a floating classroom for environmental education programs for school children.',
    goalAmount: 18000, heldAmount: 6000, deadline: hoursFromNow(250),
    location: { address: 'Södermalm, Stockholm', lat: 59.3293, lng: 18.0686 },
    organizer: { name: 'Erik Lindqvist', avatar: '' }, status: 'open', community: 'Stockholm Green', pledgeCount: 38,
    updates: [{ date: hoursFromNow(-40), text: 'Ferry inspection passed. Renovation plans underway.' }],
    pledgers: [{ name: 'Astrid N.', avatar: '', amount: 800 }],
  },
  {
    id: '26',
    title: 'Night Market Revival',
    description: 'Bring back the historic night market in Bangkok with stalls for local vendors, live music, and traditional food.',
    goalAmount: 5000, heldAmount: 4700, deadline: hoursFromNow(36),
    location: { address: 'Khao San Road, Bangkok', lat: 13.7563, lng: 100.5018 },
    organizer: { name: 'Somchai Prasert', avatar: '' }, status: 'open', community: 'Bangkok Culture', pledgeCount: 47,
    updates: [{ date: hoursFromNow(-8), text: 'Vendor applications flooding in — 60+ confirmed!' }],
    pledgers: [{ name: 'Niran T.', avatar: '', amount: 200 }],
  },
  {
    id: '27',
    title: 'Playground Accessibility Upgrade',
    description: 'Retrofit a popular playground in Seoul with wheelchair ramps, sensory play panels, and inclusive swing seats.',
    goalAmount: 9000, heldAmount: 2000, deadline: hoursFromNow(-3),
    location: { address: 'Hongdae, Seoul', lat: 37.5665, lng: 126.9780 },
    organizer: { name: 'Ji-hye Park', avatar: '' }, status: 'failed', community: 'Inclusive Seoul', pledgeCount: 14,
    updates: [], pledgers: [{ name: 'Min-jun L.', avatar: '', amount: 300 }],
  },
  {
    id: '28',
    title: 'Desert Reforestation Pilot',
    description: 'Test drought-resistant tree species in a pilot reforestation zone outside Marrakech to combat desertification.',
    goalAmount: 14000, heldAmount: 5600, deadline: hoursFromNow(220),
    location: { address: 'Ourika Valley, Marrakech', lat: 31.6295, lng: -7.9811 },
    organizer: { name: 'Youssef Amrani', avatar: '' }, status: 'open', community: 'Green Sahara', pledgeCount: 33,
    updates: [{ date: hoursFromNow(-50), text: 'Soil samples analyzed — 3 promising species identified.' }],
    pledgers: [{ name: 'Fatima B.', avatar: '', amount: 400 }],
  },
  {
    id: '29',
    title: 'Pop-up Mental Health Café',
    description: 'Launch a monthly pop-up café in Lisbon offering free peer support sessions, mindfulness workshops, and community connection.',
    goalAmount: 3000, heldAmount: 2800, deadline: hoursFromNow(20),
    location: { address: 'Alfama, Lisbon', lat: 38.7223, lng: -9.1393 },
    organizer: { name: 'Inês Costa', avatar: '' }, status: 'open', community: 'Lisbon Minds', pledgeCount: 41,
    updates: [{ date: hoursFromNow(-4), text: 'Venue confirmed for the first session next Friday!' }],
    pledgers: [{ name: 'Tomás F.', avatar: '', amount: 150 }],
  },
  {
    id: '30',
    title: 'Arctic Research Station Support',
    description: 'Fund essential supplies and satellite internet for an independent Arctic research station monitoring ice melt and wildlife migration.',
    goalAmount: 25000, heldAmount: 11000, deadline: hoursFromNow(400),
    location: { address: 'Svalbard, Norway', lat: 78.2232, lng: 15.6267 },
    organizer: { name: 'Lars Henriksen', avatar: '' }, status: 'open', community: 'Arctic Watch', pledgeCount: 82,
    updates: [{ date: hoursFromNow(-72), text: 'Starlink dish shipped — arrival expected in 3 weeks.' }],
    pledgers: [{ name: 'Ingrid S.', avatar: '', amount: 2000 }],
  },
];
